@startuml Диаграмма активности
|Арендатор|
start
:Выбор транспортного средства (т.с.) для аренды;
:Выбор даты и времени аренды;
:Попытка арендовать т.с.;
|Система|
if (Проверка можно ли арендовать данное т.с.?) then (да)
    :Блокировка т.с. на время аренды;
    |Арендатор|
    :Подтверждение аренды;
    :Оплата;
    |Система|
    if (Оплата прошла успешно?) then (да)
        :Регистрация аренды в системе;
        :Уведомление арендатора о подтверждении аренды;
        |Арендатор|
        :Получение уведомления;
    else (нет)
        |Система|
        :Сообщение об ошибке оплаты;
        :Разблокировка т.с.;
        end
    endif
else (нет)
    :Сообщение о невозможности аренды;
    end
endif
stop

@enduml
